2021-10-27 04:52:05,271 INFO    MainThread:12616 [wandb_setup.py:_flush():71] setting env: {}
2021-10-27 04:52:05,271 WARNING MainThread:12616 [wandb_setup.py:_flush():71] could not find program at train.py
2021-10-27 04:52:05,272 INFO    MainThread:12616 [wandb_setup.py:_flush():71] setting login settings: {}
2021-10-27 04:52:05,272 INFO    MainThread:12616 [wandb_init.py:_log_setup():357] Logging user logs to C:\Users\vikram\mlops_vikram\ml_docker\outputs\2021-10-27\04-51-50\wandb\run-20211027_045205-r3sm8b70\logs\debug.log
2021-10-27 04:52:05,272 INFO    MainThread:12616 [wandb_init.py:_log_setup():358] Logging internal logs to C:\Users\vikram\mlops_vikram\ml_docker\outputs\2021-10-27\04-51-50\wandb\run-20211027_045205-r3sm8b70\logs\debug-internal.log
2021-10-27 04:52:05,274 INFO    MainThread:12616 [wandb_init.py:init():390] calling init triggers
2021-10-27 04:52:05,274 INFO    MainThread:12616 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2021-10-27 04:52:05,275 INFO    MainThread:12616 [wandb_init.py:init():435] starting backend
2021-10-27 04:52:05,275 INFO    MainThread:12616 [backend.py:_multiprocessing_setup():94] multiprocessing start_methods=spawn, using: spawn
2021-10-27 04:52:05,281 INFO    MainThread:12616 [backend.py:ensure_launched():198] starting backend process...
2021-10-27 04:52:05,397 INFO    MainThread:12616 [backend.py:ensure_launched():203] started backend process with pid: 7924
2021-10-27 04:52:05,398 INFO    MainThread:12616 [wandb_init.py:init():444] backend started and connected
2021-10-27 04:52:05,404 INFO    MainThread:12616 [wandb_init.py:init():503] updated telemetry
2021-10-27 04:52:05,459 INFO    MainThread:12616 [wandb_init.py:init():533] communicating current version
2021-10-27 04:52:06,686 INFO    MainThread:12616 [wandb_init.py:init():538] got version response 
2021-10-27 04:52:06,686 INFO    MainThread:12616 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-10-27 04:52:36,697 WARNING MainThread:12616 [wandb_init.py:init():891] interrupted
Traceback (most recent call last):
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\wandb_init.py", line 870, in init
    run = wi.init()
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\wandb_init.py", line 549, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\interface\interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\interface\interface.py", line 901, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\interface\interface.py", line 799, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\interface\router.py", line 32, in get
    is_set = self._object_ready.wait(timeout)
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
